
package au.edu.unsw.soacourse.marketdataservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.4
 * 2015-04-18T19:58:50.827+10:00
 * Generated source version: 3.0.4
 */

@WebFault(name = "downloadFileFault", targetNamespace = "http://marketdataservice.soacourse.unsw.edu.au")
public class VisualiseMarketDataFaultMsg extends Exception {
    
    private au.edu.unsw.soacourse.marketdataservice.ServiceFaultType downloadFileFault;

    public VisualiseMarketDataFaultMsg() {
        super();
    }
    
    public VisualiseMarketDataFaultMsg(String message) {
        super(message);
    }
    
    public VisualiseMarketDataFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public VisualiseMarketDataFaultMsg(String message, au.edu.unsw.soacourse.marketdataservice.ServiceFaultType downloadFileFault) {
        super(message);
        this.downloadFileFault = downloadFileFault;
    }

    public VisualiseMarketDataFaultMsg(String message, au.edu.unsw.soacourse.marketdataservice.ServiceFaultType downloadFileFault, Throwable cause) {
        super(message, cause);
        this.downloadFileFault = downloadFileFault;
    }

    public au.edu.unsw.soacourse.marketdataservice.ServiceFaultType getFaultInfo() {
        return this.downloadFileFault;
    }
}
