
package au.edu.unsw.soacourse.marketdataservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.4
 * 2015-04-20T10:32:05.645+10:00
 * Generated source version: 3.0.4
 */

@WebFault(name = "summaryMarketDataFault", targetNamespace = "http://marketdataservice.soacourse.unsw.edu.au")
public class SummaryMarketFaultMsg extends Exception {
    
    private au.edu.unsw.soacourse.marketdataservice.ServiceFaultType summaryMarketDataFault;

    public SummaryMarketFaultMsg() {
        super();
    }
    
    public SummaryMarketFaultMsg(String message) {
        super(message);
    }
    
    public SummaryMarketFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public SummaryMarketFaultMsg(String message, au.edu.unsw.soacourse.marketdataservice.ServiceFaultType summaryMarketDataFault) {
        super(message);
        this.summaryMarketDataFault = summaryMarketDataFault;
    }

    public SummaryMarketFaultMsg(String message, au.edu.unsw.soacourse.marketdataservice.ServiceFaultType summaryMarketDataFault, Throwable cause) {
        super(message, cause);
        this.summaryMarketDataFault = summaryMarketDataFault;
    }

    public au.edu.unsw.soacourse.marketdataservice.ServiceFaultType getFaultInfo() {
        return this.summaryMarketDataFault;
    }
}
